packages: []
catalogs:
  build:
    unbuild: ^3.6.1
  cli:
    bumpp: ^10.2.3
    pncat: ^0.5.4
    taze: ^19.6.0
  lint:
    '@antfu/eslint-config': ^5.3.0
    eslint: ^9.35.0
    lint-staged: ^16.1.6
    simple-git-hooks: ^2.13.1
  network:
    axios: ^1.12.2
  node:
    '@clack/prompts': ^0.11.0
    ansis: ^4.1.0
    cac: ^6.7.14
    unconfig: ^7.3.3
  parser:
    fast-xml-parser: ^5.2.5
    yaml: ^2.8.1
  script:
    tsx: ^4.20.5
  test:
    vitest: ^3.2.4
  tsc:
    typescript: ^5.9.2
  types:
    '@types/node': ^24.4.0
    '@types/semver': ^7.7.1
  utils:
    semver: ^7.7.2
